### PR TITLE
Adds tap() - allows shorter syntax for chaining no side effects operations

### PR DESCRIPTION
**Pull request by ddebowczyk**
More convenient than `apply()` for chaining no side effect operations like logging or event dispatching.
Allows for shorter notation:

```php
$collection->tap(fn($item) => Event::dispatch(new ItemReceived($item)))
```

versus

```php
$collection->apply(function($item) {
   Event::dispatch(new ItemReceived($item));
   return true;
})
```

This PR:
- [+] Provides shorter notation for no side effect operations
- [-] It breaks backward compatibility
- [+] Is covered by unit tests
- [+] Has static analysis tests (psalm, phpstan)
- [+] Has documentation
- [-] Is an experimental thing

### CODE REVIEW

**Comment by drupol** [comment]
Hi,

Thanks for the PR, it LGTM ! I wasn't aware that `apply` could be a burden to use and I don't mind adding `tap` into it. I agree that the syntax is simpler.

However, let's make sure tests are passing ;)

Let me know if you need some help.

**Comment by ddebowczyk** [comment]
Frankly, i just copied tests from apply and removed irrelevant fragment
relying on boolean results. Not sure why they don't pass - any idea?

W dniu wt., 2.04.2024 o 08:06 Pol Dellaiera ***@***.***>
napisał(a):

**Comment by drupol** [comment]
There's a fundemental difference between `apply` and `tap`. Of course they can do the same things, but since `apply` must returns a boolean, it can have a different way of working than `tap`... I guess the tests you've implemented are not reflecting that.

Also, it seems that there's an issue with the syntax.

To fix the codestyle:

```
./vendor/bin/grumphp run --tasks=phpcsfixer
``` 

To run the unit tests:

```
./vendor/bin/grumphp run --tasks=phpunit
``` 

To run the static analysis tests:

```
./vendor/bin/grumphp run --tasks=psalm.phpstan
```

**Comment by ddebowczyk** [comment]
I cannot install pcov on my machine currently, so my `composer install` fails = I can't execute code checks, tests, etc on my local env. For the time being I will continue using my fork. I will try getting back to it when I find some time to set everything up properly. Thanks for quick replies.

**Comment by drupol** [comment]
I understand. I wish I could help more concretely but right now, I'm busy on some other projects sadly.

If I can give a piece of advice to have an environment ready to use to develop in `loophp/collection` is to install `nix`:

```
curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix | sh -s -- install
```

To make it short, Nix is a universal package manager working on any Linux and Mac.

Once it is installed, got in the `loophp/collection` directory and do: 

```
nix shell github:loophp/nix-shell#env-php81 --impure
```

This will take 2 to 3 minutes. Once it's done, you'll have PHP 8.1 running with PCOV and everything you need to contribute to `loophp/collection` locally.

**Comment by ddebowczyk** [comment]
Thanks again for the suggestion. I will get back with the fixes when I get tests running locally.

**Comment by drupol** [comment]
That was fast! Did you used Nix in the end?

**Comment by ddebowczyk** [comment]
Yes, Nix did the job. Thanks for suggesting it, saved me probably hours of install/config time.

**Comment by drupol** [comment]
Excellent, hope you'll use it for some other stuff too !!!

**Review by drupol — APPROVED** [review]
LGTM, I'll merge it as it is and maybe do some optimisations later on.

Thank you very much for your contribution!

**Comment by drupol** [comment]
This feature is available in the newly released version `7.6.0`.

**Pull request merged**
