### PR TITLE
update psalm type for map operation

### LINKED ISSUE #71: why does map expect return type to be a subtype
```php
class Quantity {
  public float $value;
  public string $unitCode;
}
 // psalm error here
$qtys = $value = Collection::fromIterable($qtys)->map(fn (Quantity $qty): float => $qty->value);
```
The canonical type definition of map 
`map : (T -> V) -> List T -> List V`, 
where T and V are generic type variables, as far as i know there is no requirement of V being a sub type of T in other languages

### PR DESCRIPTION
**Pull request by aszenz**
Fixes #71 , by updating map type to follow the canonical type definition

### CODE REVIEW

**Comment by drupol** [comment]
Thanks!

**Comment by drupol** [comment]
I just noticed that we should have fixed the [implementation](https://github.com/loophp/collection/blob/master/src/Operation/Map.php) as well. It seems to be a more complex job! Care to give a try?

**Comment by aszenz** [comment]
> I just noticed that we should have fixed the [implementation](https://github.com/loophp/collection/blob/master/src/Operation/Map.php) as well. It seems to be a more complex job! Care to give a try?

Sure, I'll give a try, is the fix related to the same issue or a different one

**Comment by drupol** [comment]
Feel free to do what suits you best :) thanks !

**Comment by aszenz** [comment]
@drupol 
I somehow kept wanting to do it, but couldn't, anyways i made a pr, not sure i fully understand how the map operation works for a collection of callable's so let me know if there's anything obliviously wrong with it

**Pull request merged**
