### PR TITLE
refactor: Update cross `product` operation in point free style.

### PR DESCRIPTION
**Pull request by drupol**
This PR:

* [x] Update `Product` in point free style.
* [x] Has unit tests (phpspec)
* [x] Has static analysis tests (psalm, phpstan)

### CODE REVIEW

**Comment by drupol** [comment]
It seems that there is an issue with the latest PSalm version (4.9.3)... investigating.

**Comment by drupol** [comment]
I updated `drupol/php-conventions` so it doesn't install version 4.9.3 of Psalm.

**Review by AlexandruGG — APPROVED** [review]
I cannot see the Psalm issue anymore but looks like you sorted it by restricting the version so should be fine for now.

On a separate note, I think this new form is extremely difficult to follow and understand 😅.
What do you think of using some variables just to make it a bit easier to follow? It shouldn't affect performance too much.

For example, storing [this closure](https://github.com/loophp/collection/blob/91535c35d6c341c8bf8b313a410a5fa00636622c/src/Operation/Product.php#L43-L62) in a variable. Same for the others, and then combining in the Pipe. Alternatively, we could add comments to show what each one represents?

**Comment by AlexandruGG** [comment]
@drupol auto-merge got me again 😄

**Pull request merged**
