### PR TITLE
Update annotations - remove @psalm prefix

### PR DESCRIPTION
**Pull request by drupol**
This PR

* [x] Replace @psalm-template with @template.
* [x] Replace @psalm-param with @param.
* [x] Replace @psalm-var with @var.
* [x] Replace @psalm-return with @return.
* [x] Fix code-style.

### CODE REVIEW

**Comment by drupol** [comment]
@AlexandruGG This PR is opening the Pandora box! It's driving me crazy :sob:

**Comment by AlexandruGG** [comment]
> @AlexandruGG This PR is opening the Pandora box! It's driving me crazy 😭

I know the pain 😅 . I have a PR for some more stuff, but I wasn't expecting you'd do these all in one because it's quite a lot to fix haha.

We could do them incrementally as that might be easier, I can do it as I add the checks in `tests/static-analysis`

**Comment by AlexandruGG** [comment]
@drupol I fixed the issues here but I'm unable to push to your PR :( 

```
remote: Permission to loophp/collection.git denied to AlexandruGG.
fatal: unable to access 'https://github.com/loophp/collection.git/': The requested URL returned error: 403
```

**Comment by AlexandruGG** [comment]
> @drupol I fixed the issues here but I'm unable to push to your PR :(
> 
> ```
> remote: Permission to loophp/collection.git denied to AlexandruGG.
> fatal: unable to access 'https://github.com/loophp/collection.git/': The requested URL returned error: 403
> ```
I'm guessing it's because I'm not a [collaborator](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository). Let me know if you could add me but if not no worries I could use git archive I think

**Comment by drupol** [comment]
I think you can base your branch on mine. Driving to Afup, I will check deeper when I arrive.

**Comment by drupol** [comment]
Closed in favor of #101

**Pull request closed without merging**
